# Generated by Django 4.2.6 on 2023-11-01 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('DoctorId', models.AutoField(primary_key=True, serialize=False)),
                ('DoctorName', models.CharField(max_length=50)),
                ('DoctorSpecialty', models.CharField(max_length=50)),
                ('DoctorUserName', models.CharField(max_length=50)),
                ('DoctorHashedPassword', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('PatientId', models.AutoField(primary_key=True, serialize=False)),
                ('PatientName', models.CharField(max_length=50)),
                ('PatientUserName', models.CharField(max_length=50)),
                ('PatientHashedPassword', models.CharField(max_length=255)),
                ('PatientMdedicalHistory', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('SlotId', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Is_available', models.BinaryField()),
                ('DoctorId', models.IntegerField()),
                ('StartTime', models.TimeField()),
                ('EndTime', models.TimeField()),
                ('doctorSlotFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_reservationApp.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('AppointmentId', models.AutoField(primary_key=True, serialize=False)),
                ('AppointmentPatientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_reservationApp.patient')),
                ('AppointmentSlotNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_reservationApp.slot')),
            ],
        ),
    ]
