# Generated by Django 4.2.6 on 2023-11-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_reservationApp', '0002_remove_slot_doctorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='Is_available',
            field=models.BooleanField(),
        ),
    ]
